/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "common": {
        "HELLO_WORLD": string;
    };
    "error": {
        "NOT_FOUND": string;
        "CANNOT_DELETE_HAVE_CHILDREN": string;
    };
    "label": {
        "ID": string;
        "USER": string;
        "ROLE": string;
        "NAME": string;
        "USERNAME": string;
        "EMAIL": string;
        "PASSWORD": string;
        "CONFIRM_PASSWORD": string;
        "PAGE": string;
        "LIMIT": string;
        "SEARCH": string;
        "ORDER_BY": string;
        "ORDER_DIR": string;
        "ROLE_ID": string;
    };
    "validation": {
        "IS_NOT_EMPTY": string;
        "IS_STRING": string;
        "IS_STRONG_PASSWORD": string;
        "IS_EMAIL": string;
        "MATCH_PASSWORD": string;
        "IS_NOT_EXISTS": string;
        "IS_EXISTS": string;
        "IS_IN": string;
        "IS_UUID": string;
        "IS_INT": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
