/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "common": {
        "HELLO_WORLD": string;
    };
    "error": {
        "NOT_FOUND": string;
        "CANNOT_DELETE_HAVE_CHILDREN": string;
    };
    "label": {
        "id": string;
        "user": string;
        "username": string;
        "email": string;
        "password": string;
        "confirmPassword": string;
        "orderBy": string;
    };
    "validation": {
        "IS_NOT_EMPTY": string;
        "IS_STRING": string;
        "IS_STRONG_PASSWORD": string;
        "IS_EMAIL": string;
        "MATCH_PASSWORD": string;
        "IS_NOT_EXISTS": string;
        "IS_EXISTS": string;
        "IS_IN": string;
        "IS_UUID": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
